config/routes.rb
Rails.application.routes.draw do
  root "calendars#index"

  resources :calendars, :categories do
    resources :notes, :participants, :tasks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calendar.rb
class Calendar < ApplicationRecord
  has_many :notes, dependent: :destroy
  has_many :participants, dependent: :destroy
  has_many :tasks

  validates :day, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 5 }
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :calendar
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :calendar
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :calendar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  def index
    @calendars = Calendar.all
  end

  def show
    @calendar = Calendar.find(params[:id])
  end

  def new
    @calendar = Calendar.new
  end

  def create
    @calendar = Calendar.new(calendar_params)

    if @calendar.save
      redirect_to @calendar
    else
      render :new
    end
  end

  def edit
    @calendar = Calendar.find(params[:id])
  end

  def update
    @calendar = Calendar.find(params[:id])

    if @calendar.update(calendar_params)
      redirect_to @calendar
    else
      render :edit
    end
  end

  private
    def calendar_params
      params.require(:calendar).permit(:day)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
     @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to @category
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to root_path
  end

  private
    def category_params
      params.require(:category).permit(:name, :description)
    end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def create
   @calendar = Calendar.find(params[:calendar_id])
   @note = @calendar.notes.create(note_params)
   redirect_to calendar_path(@calendar)
 end

 def destroy
    @calendar = Calendar.find(params[:calendar_id])
    @note = @calendar.notes.find(params[:id])
    @note.destroy
    redirect_to calendar_path(@calendar)
  end

 private
   def note_params
     params.require(:note).permit(:description)
   end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  def create
   @calendar = Calendar.find(params[:calendar_id])
   @participant = @calendar.participants.create(participant_params)
   redirect_to calendar_path(@calendar)
 end

 def destroy
    @calendar = Calendar.find(params[:calendar_id])
    @participant = @calendar.participants.find(params[:id])
    @participant.destroy
    redirect_to calendar_path(@calendar)
  end

 private
   def participant_params
     params.require(:participant).permit(:name)
   end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def create
   @calendar = Calendar.find(params[:calendar_id])
   @task = @calendar.tasks.create(task_params)
   redirect_to calendar_path(@calendar)
 end

 def destroy
    @calendar = Calendar.find(params[:calendar_id])
    @task = @calendar.tasks.find(params[:id])
    @task.destroy
    redirect_to calendar_path(@calendar)
  end

 private
   def task_params
     params.require(:task).permit(:name, :description, :due_date, :category)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/calendars/_form.html.erb
<%= form_with model: @calendar do |form| %>
  <div>
    <%= form.label :day %><br>
    <%= form.text_field :day %>
    <% @calendar.errors.full_messages_for(:day).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/calendars/edit.html.erb
<h1>Edit Day</h1>

<%= render "form", calendar: @calendar %>

app/views/calendars/index.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
* {box-sizing: border-box;}
ul {list-style-type: none;}

.colorLink {
  color: #BD5151;
}

.month {
  padding: 33px 25px;
  width: 100%;
  background: #E3EFFA;
  text-align: center;
}

.month ul {
  margin: 0;
  padding: 0;
}

.month ul li {
  color: black;
  font-size: 20px;
  text-transform: uppercase;
  letter-spacing: 20px;
}

.month .prev {
  float: left;
  padding-top: 10px;
}

.month .next {
  float: right;
  padding-top: 10px;
}

.weekdays {
  margin: 0;
  padding: 15px 0;
  background-color: #6B97C1;
}

.weekdays li {
  display: inline-block;
  width: 13.6%;
  color: #FFFFFF;
  text-align: center;
}

.days {
  padding: 25px 0;
  background: #EFF6FD;
  margin: 0;
}

.days li {
  list-style-type: none;
  display: inline-block;
  width: 13.6%;
  text-align: center;
  margin-bottom: 30px;
  font-size:12px;
  color: #777;
}

.days li .active {
  padding: 5px;
  background: #1abc9c;
  color: white
}

(max-width:720px) {
  .weekdays li, .days li {width: 13.1%;}
}

(max-width: 420px) {
  .weekdays li, .days li {width: 12.5%;}
  .days li .active {padding: 2px;}
}

(max-width: 290px) {
  .weekdays li, .days li {width: 12.2%;}
}

body {
  font-family: "Lato", sans-serif;
}

</style>
</head>
<body>

<div class="month">
  <ul>
    <li>
      Diciembre ---
      <span style="font-size:20px">2021</span>
    </li>
  </ul>
</div>

<ul class="weekdays">
  <li><b>-- Lunes --</b></li>
  <li><b>-- Martes --</b></li>
  <li><b>-- Miércoles --</b></li>
  <li><b>-- Jueves --</b></li>
  <li><b>-- Viernes --</b></li>
  <li><b>-- Sábado --</b></li>
  <li><b>-- Domingo --</b></li>
</ul>

<ul class="days">
  <li><b>29</b></li>
  <li><b>30</b></li>
    <% @calendars.each do |calendar| %>
        <li><%= link_to calendar.day, calendar, class: "colorLink", class: "btn btn-outline-dark" %></li>
    <% end %>
<li><b>01</b></li>
<li><b>02</b></li>

<!--<li> <%= link_to "New Day", new_calendar_path %></li>-->
</ul>

</body>
</html>

app/views/calendars/new.html.erb
<h1>New Day</h1>

<%= render "form", calendar: @calendar %>

app/views/calendars/show.html.erb
<style media="screen">
  .sc {
    padding: 50px;
    background: #EFF6FD;
  }
</style>

<div align="left"><div align="center" class="sc"><h4>--- Día <%= @calendar.day %> de Diciembre 2021 ---</h4> <img src="https://cdn-icons-png.flaticon.com/512/42/42288.png" width="30" height="30"></div>
<!--<li><%= link_to "Edit", edit_calendar_path(@calendar) %></li>-->

<div class="sc ">
<div class="row gy-5">
  <div class="col-12">
    <h4>Notas:</h4>
    <div class="p-3 border bg-light"> <%= render @calendar.notes %> </div>
  </div>
</div>

<p></p>

  <div class="row gy-5">
    <div class="col-12">
      <h4>Tareas:</h4>
      <div class="p-3 border bg-light"><%= render @calendar.tasks %></div>
    </div>
  </div>

<p></p>

<div class="row gy-5">
  <div class="col-12">
    <h4>Participantes:</h4>
    <div class="p-3 border bg-light"><%= render @calendar.participants %></div>
  </div>
</div>

<br></br>
<div align="center"><h4>--- Agregar Eventos ---</h4> <img src="https://cdn-icons-png.flaticon.com/512/45/45533.png" width="40" height="40"></div>
<br></br>

<div class="container">
  <div class="row">
    <div class="col">
      <h4>Agregar una tarea:</h4>
      <p></p>
      <%= render 'tasks/form' %>
    </div>
    <div class="col">
      <h4>Agregar un participante:</h4>
      <p></p>
      <%= render 'participants/form' %>
    </div>
    <div class="col col-lg-3">
      <h4>Agregar una nota:</h4>
      <p></p>
      <%= render 'notes/form' %> </div>
    </div>
  </div>
</div>

app/views/categories/_form.html.erb
<%= form_with model: @category do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% @category.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %><br>
    <% @category.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <br></br>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<style>
  .sc {
    padding: 20px;
    background: #EFF6FD;
  }
  </style>
<div class="sc"> <h1>Editar Categoría</h1>

  <p></p>

<%= render "form", category: @category %> </div>

app/views/categories/index.html.erb
<style>
  .sc {
    padding: 80px;
    background: #EFF6FD;
  }
  </style>

  <div class="sc">

  <div class="row gy-5" align="left";>
    <div class="col-12">
      <h4>Categorías:</h4>
      <div class="p-3 border bg-light">
        <% @categories.each do |category| %>
          <p>
            <%= link_to category.name, category %>
          </p>
        <% end %></div>
    </div>
  </div>

<ol>
  <br> <%= link_to "Agregar nueva categoría", new_category_path %> </br>
</ol>
</div>

app/views/categories/new.html.erb
<style>
  .sc {
    padding: 20px;
    background: #EFF6FD;
  }
  </style>

<div class="sc"><h1>Nueva Categoría</h1>

<%= render "form", category: @category %> </div>

app/views/categories/show.html.erb
<style>
  .sc {
    padding: 20px;
    background: #EFF6FD;
  }
  </style>

<div class="sc">

  <div class="row gy-5">
    <div class="col-12">
      <h2><%= @category.name %></h2>
      <div class="p-3 border bg-light"> - <%= @category.description %> - </div>
    </div>
  </div>

<p></p>

<ul>
   <%= link_to "Editar Categoría", edit_category_path(@category) %>
   <p></p>
   <%= button_to "Eliminar Categoría", category_path(@category), method: :delete, data: { confirm: "¿Estás seguro?" } %>
</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scheduler</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <div align="center"><body>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #6B97C1;">
    <img src="https://cdn-icons-png.flaticon.com/512/42/42288.png" width="25" height="25">
  <div class="container-fluid">
    <a class="navbar-brand"><b>My Scheduler</b></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/calendars/">Agenda</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/categories/">Categorías</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

    <%= yield %>
  </body></div>
</html>

app/views/notes/_form.html.erb
<%= form_with model: [ @calendar, @calendar.notes.build ] do |form| %>
  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>
  <p>
    <input class="btn btn-outline-dark" <%= form.submit %>
  </p>
<% end %>

app/views/notes/_note.html.erb
<p>
  <strong>Descripción:</strong>
  <%= note.description %>
</p>

<p> <%= button_to 'Eliminar nota', [note.calendar, note], method: :delete, data: { confirm: "¿Estás seguro?" } %> </p>

app/views/participants/_form.html.erb
<%= form_with model: [ @calendar, @calendar.participants.build ] do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <input class="btn btn-outline-dark" <%= form.submit %>
  </p>
<% end %>

app/views/participants/_participant.html.erb
<p>
  <strong>Nombre:</strong>
  <%= participant.name %>
</p>

<p> <%= button_to 'Eliminar participante', [participant.calendar, participant], method: :delete, data: { confirm: "¿Estás seguro?" }  %> </p>

app/views/tasks/_form.html.erb
<%= form_with model: [ @calendar, @calendar.tasks.build ] do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>
  <p>
    <%= form.label :due_date %><br>
    <%= form.date_field :due_date %>
  </p>
  <p>
    <%= form.label :category %><br>
    <%= form.text_field :category %>
  </p>
  <p>
    <input class="btn btn-outline-dark" <%= form.submit %>
  </p>
<% end %>

app/views/tasks/_task.html.erb
<p>
  <strong>Nombre:</strong>
  <%= task.name %>
</p>

<p>
  <strong>Descripción:</strong>
  <%= task.description %>
</p>

<p>
  <strong>Fecha de evento:</strong>
  <%= task.due_date %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= task.category %>
</p>

<p> <%= button_to 'Eliminar tarea', [task.calendar, task], method: :delete, data: { confirm: "¿Estás seguro?" } %> </p>